Unescape URL encoded key parameter on get
DataDog/temporal-large-payload-codec pull request #70
Opened 2024-01-16 13:09 UTC by lminaudier

Some CLI tools like httpie are always encoding URL parameters. If we don't decode the parameter, we end up hitting 404s. This patch properly handles decoding the key parameter when appropriate.

2024-01-31 12:21 UTC, hferentschik requested changes

2024-01-31 12:21 UTC, hferentschik commented on server/handler/v2/handler.go
> +	key, err := url.QueryUnescape(keyParam)
What needs unescaping in our key? The `/` probably, right? 
Looks basically ok to me. Do you mind adding a test. If you don't want to add a new test on the handler level, I think you can just add a test case to `server_test` where we already have a retrieval test. Just add another case where the `/` is escaped.

2024-01-31 12:23 UTC, hferentschik commented
LGTM. Would you mind for completeness creating an issue in the GitHub issue tracker for this and prefix the commits message with "fix: bla bla bla". I'd like to eventually configure semantic release on this repo in which case the commit message drives the new version.

2024-02-20 09:50 UTC, hferentschik commented
@lminaudier ^^ (not sure whether you forgot about this one :-))

2024-02-20 09:52 UTC, lminaudier commented
It's lower priority on my todo list. I will address eventually (creating proper bug report, test, ...) but it's not super important :)

Thanks for the reminder though! 🙇🏻

2024-08-02 08:49 UTC, hferentschik reviewed
lgtm.

Mind doing me a favour and squashing the two commits and create a commit in the [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0/)?

I'd like to be able to cut release notes and do versioning by convention. go-releaser is already setup which is the first step. 

See also https://github.com/DataDog/temporal-large-payload-codec/blob/main/CONTRIBUTING.md#releasing

2024-08-02 09:52 UTC, hferentschik commented
/merge

2024-08-02 12:32 UTC, hferentschik commented
/remove

2024-08-02 12:33 UTC, hferentschik approved these changes

2024-08-02 12:33 UTC, merged